# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:latest
    container_name: springreddit_mysql
    restart: always
    environment:
      MYSQL_DATABASE: springredditclone
      MYSQL_ROOT_PASSWORD: c%vsx!32ZBjc0Tn
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    # (this is just an example, not intended to be a production configuration)
