version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c%vsx!32ZBjc0Tn
      MYSQL_DATABASE: springredditclone_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "3307:3306"  # Maps MySQL's internal port 3306 to host port 3307
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: reddit-clone
    container_name: springredditclone
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/spring-reddit-clone
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: c%vsx!32ZBjc0Tn  # Ensure this matches the MYSQL_ROOT_PASSWORD
